export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'
export const SAVE_DAYS = 'SAVE_DAYS'
export const SELECT_TO_STATE = 'SELECT_TO_STATE'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'
export const LOAD_ARTICLE = 'LOAD_ARTICLE'
export const LOAD_COMMENTS = 'LOAD_COMMENTS'

